FROM node:22-bookworm-slim
WORKDIR /app

COPY package.json ./
COPY backend/package.json backend/package.json
COPY frontend/package.json frontend/package.json

RUN npm install

COPY . .

EXPOSE 8080 5173
CMD ["npm", "run", "dev"]
